learnromanian:
  rest:
    version: 0.0.1
  log:
    requests:
      enabled: true
spring:
  profiles:
    active: "dev"
  servlet:
    multipart:
      max-file-size: -1
      enabled: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
  data:
    rest:
      base-path: /repo
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  servlet:
    context-path: /learnromanian/v0.0.1/api
  port: 8081