learnromanian:
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
server:
  servlet:
    context-path: /learnromanian/${APP_VERSION}/api
  port: ${RUNNING_PORT}
authentication:
  token:
    secret: ${SECRET_KEY}
registration:
  validation-token:
    expiration: ${VERIFICATION_TOKEN_EXPIRATION_MINUTES}
email:
  from:
    address: ${EMAIL_SENDER}
    name: ${EMAIL_SENDER_NAME}
  api:
    key: ${EMAIL_API_KEY}
    secret: ${EMAIL_API_SECRET}
webapp:
  url: ${WEBAPP_URL}