name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  package_and_build:
    name: Build app using Maven and create Docker image
    runs-on: self-hosted
    steps:
      - name: Set environment variables
        run: export M2_HOME="/opt/apache-maven-3.9.2"
      - uses: actions/checkout@v3
      - name: Package using Maven
        run: mvn package
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag learnromanian-rest:${{ vars.APP_VERSION }}
      - name: Echo directories
        run: for dir in /home/*/; do echo "$dir"; done
