name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Package with Maven
        run: /opt/apache-maven-3.9.2/bin/mvn package
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag learnromanian-rest:${{ vars.APP_VERSION }}.$(date +%s)
