name: Tests Runner

on: [push]

jobs:
  run_tests:
    name: Run automated tests
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests using Maven
        run: /opt/apache-maven-3.9.2/bin/mvn test -DRUNNING_PORT=${{ vars.RUNNING_PORT }}  -DSECRET_KEY=${{ secrets.SECRET_KEY }}"
